import type { CategoryType } from '@prisma/client';

interface DefaultCategory {
  name: string;
  icon: string;
  color: string;
  type: CategoryType;
  keywords: string[];
}

export const DEFAULT_CATEGORIES: DefaultCategory[] = [
  {
    name: 'Alimentacion',
    icon: 'utensils',
    color: '#FF6B6B',
    type: 'EXPENSE',
    keywords: [
      'supermercado',
      'restaurante',
      'comida',
      'almuerzo',
      'cena',
      'desayuno',
      'cafe',
      'pizza',
      'hamburguesa',
      'mercado',
      'grocery',
      'food',
    ],
  },
  {
    name: 'Transporte',
    icon: 'car',
    color: '#4ECDC4',
    type: 'EXPENSE',
    keywords: [
      'uber',
      'taxi',
      'gasolina',
      'nafta',
      'bus',
      'metro',
      'subte',
      'peaje',
      'estacionamiento',
      'transport',
      'gas',
    ],
  },
  {
    name: 'Entretenimiento',
    icon: 'gamepad-2',
    color: '#45B7D1',
    type: 'EXPENSE',
    keywords: [
      'cine',
      'netflix',
      'spotify',
      'juego',
      'concierto',
      'teatro',
      'streaming',
      'suscripcion',
      'entertainment',
    ],
  },
  {
    name: 'Compras',
    icon: 'shopping-bag',
    color: '#F7DC6F',
    type: 'EXPENSE',
    keywords: [
      'ropa',
      'zapatos',
      'amazon',
      'tienda',
      'mall',
      'shopping',
      'electronica',
      'tecnologia',
    ],
  },
  {
    name: 'Salud',
    icon: 'heart-pulse',
    color: '#82E0AA',
    type: 'EXPENSE',
    keywords: [
      'farmacia',
      'medico',
      'doctor',
      'hospital',
      'medicina',
      'gym',
      'gimnasio',
      'dentista',
      'health',
    ],
  },
  {
    name: 'Servicios',
    icon: 'receipt',
    color: '#BB8FCE',
    type: 'EXPENSE',
    keywords: [
      'luz',
      'agua',
      'gas',
      'internet',
      'telefono',
      'celular',
      'electricidad',
      'alquiler',
      'renta',
      'bills',
      'seguro',
    ],
  },
  {
    name: 'Educacion',
    icon: 'graduation-cap',
    color: '#5DADE2',
    type: 'EXPENSE',
    keywords: [
      'curso',
      'libro',
      'universidad',
      'escuela',
      'clase',
      'tutorial',
      'educacion',
      'education',
    ],
  },
  {
    name: 'Otros',
    icon: 'circle-ellipsis',
    color: '#AEB6BF',
    type: 'EXPENSE',
    keywords: [],
  },
  {
    name: 'Salario',
    icon: 'banknote',
    color: '#27AE60',
    type: 'INCOME',
    keywords: ['salario', 'sueldo', 'nomina', 'pago', 'salary', 'payroll'],
  },
  {
    name: 'Freelance',
    icon: 'laptop',
    color: '#2ECC71',
    type: 'INCOME',
    keywords: ['freelance', 'proyecto', 'consulta', 'contrato', 'cliente'],
  },
  {
    name: 'Inversiones',
    icon: 'trending-up',
    color: '#1ABC9C',
    type: 'INCOME',
    keywords: ['dividendo', 'interes', 'rendimiento', 'inversion', 'investment', 'dividend'],
  },
  {
    name: 'Otros ingresos',
    icon: 'plus-circle',
    color: '#58D68D',
    type: 'INCOME',
    keywords: [],
  },
];
